export enum ViewTree {
  HOME = "home",
  ANNOUNCEMENT = "announcement",
  ANNOUNCEMENT_TERMS_SERVICE = "announcement/edit-announcement",
  EDIT_ANNOUNCEMENT = "announcement/edit-announcement/forms",
  EDIT_FUNERAL_FUND = "edit-funeral-fund",
  FUND_TERMS_SERVICE = "announcement/edit-funeral-fund",
  FUND_LIST = "announcement/edit-funeral-fund/list",
  FAMILY_FUND = "announcement/edit-funeral-fund/family-fund",
  CHARITABLE_FUND = "announcement/edit-funeral-fund/charitable-fund",
  LIVE_PREVIEW = "live-preview",
  ANNOUNCEMENTS_OVERVIEW = "home/announcements",
  CONDOLENCES_OVERVIEW = "home/condolences",
  DONATIONS_OVERVIEW = "home/donations",
  APPRECIATIONS_OVERVIEW = "home/appreciations",
  ANALYTICS_OVERVIEW = "home/analytics",
  ANALYTICS_INNER = "home/analytics/inner/announcement-analytic",
  ALL_THANK_YOUS = "home/donations/inner/thank-yous",
  ALL_CONDOLENCES = "home/condolences/inner/all-condolences",
  ALL_APPRECIATIONS = "home/appreciations/inner/all-appreciations",
}
